### ISSUE TITLE
There is no description about this project

### ISSUE THREAD

**Issue by danse** [andrewthad/yesod-crud-persist#1]
This is one of the CRUD projects for Yesod which was updated most recently, i would like to find out more about it. Would you mind adding a short README?

**Comment by andrewthad** [comment]
Yeah, I'll give that a shot.

**Comment by andrewthad** [comment]
I've added a readme. I'll try to improve the documentation of this more though. I had originally come up with an approach that involved subsites. It was alright for me to use (since I had written it and understood it), so I just never bothered to improve it, even after I thought of a better way to implement it. Recently though, there were people working for me on a project that involved `yesod-crud-persist`, and I realized that I really needed to move to the better abstraction. So, I would say that it's pretty stable right now, and I like the design. I'll try to put up a minimal, single-file example at some point. If you end up using this, feel free to open up an issue for any questions you have, and that will help me know where more documentation should be added.

**Comment by danse** [comment]
To be honest, from a CRUD library for Yesod, i expect as little code as possible. I found this repo searching for Haskell equivalents of Django's admin site. That is a CRUD interface with configuration close to zero. The only configuration there is one line saying "expose this data model to the CRUD".

I would use a server-side CRUD for agile data modeling which involves the client or the user. I am interested in showing the data model in the most transparent way to the client, to make sure that we are on the same page before developing more bespoke or sophisticated functionality. To this extent, i am looking for a CRUD functionality which doesn't require any coding, besides the definition of the data model. An alternative i am considering is also Postgrest + ng-admin.

Anyway, the README looks good! Thanks for taking the time! :+1:

**Comment by andrewthad** [comment]
Thanks for letting me know what kind of things you're looking for. This definitely does not suit your use case. I have played around with using `Generic` to generate a form from a data type, but unfortunately it's not something that's ever been useful for me. If I ever do end up adding features that make this library offer more of a zero-configuration setup, I'll ping you.

**Comment by danse** [comment]
You might be interested into https://github.com/league/yesod-crud, it is a project similar to this one. I am not very knowledgeable about Yesod so i can't appreciate the difference, besides that one using subsites
